# Generated by Django 3.2.25 on 2024-08-16 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTableStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(max_length=16, unique=True)),
                ('Firstname', models.CharField(max_length=100)),
                ('Middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('Lastname', models.CharField(max_length=100)),
                ('Prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Address', models.CharField(max_length=250)),
                ('Number', models.CharField(max_length=11)),
                ('Course', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=50)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profileImage/')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('archivedStudents', models.CharField(choices=[('NotArchive', 'NotArchive'), ('Archive', 'Archive'), ('UnArchive', 'Unarchive')], default='NotArchive', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('IN', 'Time In'), ('OUT', 'Time Out')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='time_logs/')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.datatablestudents')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.datatablestudents')),
            ],
        ),
    ]
