# Generated by Django 5.1 on 2024-08-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_timelog_duration_alter_timelog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
