# Generated by Django 5.1 on 2024-09-11 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_timelog_action_alter_timelog_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='action',
            field=models.CharField(choices=[('IN', 'Time In'), ('OUT', 'Time Out')], max_length=10),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=5, default=0.00),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='time_logs/'),
        ),
        migrations.CreateModel(
            name='TableSubmittedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.datatablestudents')),
            ],
        ),
    ]
