# Generated by Django 5.1 on 2024-09-15 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tablerequirements'),
        ('students', '0005_alter_timelog_action_alter_timelog_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSubmittedRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file', models.FileField(upload_to='student_submissions/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tablerequirements')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.datatablestudents')),
            ],
        ),
    ]
