# Generated by Django 5.1 on 2024-09-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_tablesubmittedrequirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablesubmittedrequirement',
            name='requirement',
        ),
    ]
