# Generated by Django 5.1 on 2024-09-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_datatablestudents_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatablestudents',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pendingapplication',
            name='status',
            field=models.CharField(default='PendingApplication', max_length=100),
        ),
        migrations.AlterField(
            model_name='rejectapplication',
            name='status',
            field=models.CharField(default='RejectedApplication', max_length=100),
        ),
    ]
