# Generated by Django 5.1 on 2024-09-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_rename_address_pendingapplication_pendingaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejectapplication',
            old_name='Address',
            new_name='RejectAddress',
        ),
        migrations.RenameField(
            model_name='rejectapplication',
            old_name='Course',
            new_name='RejectCourse',
        ),
        migrations.RenameField(
            model_name='rejectapplication',
            old_name='Email',
            new_name='RejectEmail',
        ),
        migrations.RenameField(
            model_name='rejectapplication',
            old_name='Firstname',
            new_name='RejectFirstname',
        ),
        migrations.RenameField(
            model_name='rejectapplication',
            old_name='Lastname',
            new_name='RejectLastname',
        ),
        migrations.RenameField(
            model_name='rejectapplication',
            old_name='Middlename',
            new_name='RejectMiddlename',
        ),
        migrations.RenameField(
            model_name='rejectapplication',
            old_name='Number',
            new_name='RejectNumber',
        ),
        migrations.RenameField(
            model_name='rejectapplication',
            old_name='Password',
            new_name='RejectPassword',
        ),
        migrations.RenameField(
            model_name='rejectapplication',
            old_name='Prefix',
            new_name='RejectPrefix',
        ),
        migrations.RenameField(
            model_name='rejectapplication',
            old_name='status',
            new_name='RejectStatus',
        ),
        migrations.RenameField(
            model_name='rejectapplication',
            old_name='StudentID',
            new_name='RejectStudentID',
        ),
        migrations.RenameField(
            model_name='rejectapplication',
            old_name='Username',
            new_name='RejectUsername',
        ),
        migrations.RenameField(
            model_name='rejectapplication',
            old_name='Year',
            new_name='RejectYear',
        ),
    ]
