# Generated by Django 5.1 on 2024-09-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_rename_address_rejectapplication_rejectaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingapplication',
            name='PendingStatusArchive',
            field=models.CharField(default='NotArchive', max_length=100),
        ),
        migrations.AddField(
            model_name='rejectapplication',
            name='RejectStatusArchive',
            field=models.CharField(default='NotArchive', max_length=100),
        ),
    ]
