# Generated by Django 5.1 on 2024-09-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='status',
            field=models.CharField(default='No Remarks', max_length=10),
        ),
    ]
