# Generated by Django 5.1 on 2024-09-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_grade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatablestudents',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
