# Generated by Django 5.1 on 2024-10-02 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_datatablestudents_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesubmittedrequirement',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
