# Generated by Django 5.1 on 2024-10-02 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_tablesubmittedrequirement_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfDocs', models.CharField(max_length=255)),
                ('approved_file', models.FileField(upload_to='approved_documents/')),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.datatablestudents')),
            ],
        ),
    ]
