# Generated by Django 5.1 on 2024-10-02 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_approveddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnToRevisionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfDocs', models.CharField(max_length=255)),
                ('revision_file', models.FileField(upload_to='revision_documents/')),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('revision_reason', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.datatablestudents')),
            ],
        ),
    ]
