# Generated by Django 5.1 on 2024-10-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_returntorevisiondocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('score', models.IntegerField(default=0)),
                ('submitted_file', models.FileField(upload_to='time_sheets/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.datatablestudents')),
            ],
        ),
    ]
