# Generated by Django 5.1 on 2024-10-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_timesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='action',
            field=models.CharField(choices=[('IN', 'Time In'), ('OUT', 'Time Out'), ('LUNCH OUT', 'Lunch Out'), ('LUNCH IN', 'Lunch In')], max_length=10),
        ),
    ]
