# Generated by Django 5.1 on 2024-10-05 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_lunchlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='action',
            field=models.CharField(choices=[('IN', 'Time In'), ('OUT', 'Time Out')], max_length=10),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.datatablestudents')),
            ],
        ),
    ]
