# Generated by Django 5.1 on 2024-10-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_alter_grade_docs_alter_grade_evaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatablestudents',
            name='Year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datatablestudents',
            name='archivedStudents',
            field=models.CharField(choices=[('NotArchive', 'NotArchive'), ('Archive', 'Archive')], default='NotArchive', max_length=30),
        ),
    ]
