# Generated by Django 5.1 on 2024-10-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_alter_datatablestudents_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingapplication',
            name='PendingYear',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
