# Generated by Django 5.1 on 2024-10-15 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_alter_pendingapplication_pendingyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatablestudents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datatablestudents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
