# Generated by Django 5.1 on 2024-10-16 01:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_datatablestudents_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rejectapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rejectapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
