# Generated by Django 5.1 on 2024-10-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_pendingapplication_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='timelog',
            name='action',
            field=models.CharField(choices=[('IN', 'Time In'), ('OUT', 'Time Out'), ('LUNCH IN', 'Lunch In'), ('LUNCH OUT', 'Lunch Out')], max_length=10),
        ),
    ]
