# Generated by Django 5.1 on 2024-10-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_listrequirement_alter_timelog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatablestudents',
            name='ContactNumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='datatablestudents',
            name='HTE',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datatablestudents',
            name='NameOfSupervisor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
