# Generated by Django 5.1 on 2024-10-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_datatablestudents_contactnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatablestudents',
            old_name='HTE',
            new_name='Department',
        ),
        migrations.AddField(
            model_name='datatablestudents',
            name='HTEAddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
