# Generated by Django 5.1 on 2024-08-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='announcement/')),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('Description', models.CharField(max_length=450)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
