# Generated by Django 5.1 on 2024-08-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_storeactivitylogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeactivitylogs',
            old_name='additional_info',
            new_name='description',
        ),
    ]
