# Generated by Django 5.1 on 2024-09-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_additional_info_storeactivitylogs_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfFile', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='ojt_requirements/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
