# Generated by Django 5.1 on 2024-09-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tablerequirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfContent', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(upload_to='content/')),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
