# Generated by Django 5.1 on 2024-09-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tablecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(default='Coordinator', max_length=100),
        ),
    ]
